// TaskFlow.MobileApp/ViewModels/BaseViewModel.cs

using CommunityToolkit.Mvvm.ComponentModel;

namespace TaskFlow.MobileApp.ViewModels
{
    public partial class BaseViewModel : ObservableObject
    {
        [ObservableProperty]
        [NotifyPropertyChangedFor(nameof(IsNotBusy))]
        // The private field for the IsBusy property
        private bool isBusy;

        [ObservableProperty]
        private string title = string.Empty;

        // FIX: This property now correctly references the public 'IsBusy' property
        // that is generated by the MVVM Toolkit, not the private '_isBusy' field.
        public bool IsNotBusy => !IsBusy;
    }
}
